# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('logo', models.ImageField(upload_to='shows/logos', verbose_name='Logo')),
                ('card', models.ImageField(upload_to='shows/cards', verbose_name='Card')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
