# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 18:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    replaces = [(b'shows', '0003_show_duration'), (b'shows', '0004_show_published'), (b'shows', '0005_auto_20170507_1601')]

    dependencies = [
        ('shows', '0002_auto_20170507_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 1800), verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='show',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('end', models.DateTimeField(blank=True, verbose_name='End')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelManagers(
            name='show',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='shows.Show'),
        ),
    ]
