# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 15:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20170507_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 1800), verbose_name='Duration'),
        ),
    ]
